on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  create:
  workflow_dispatch:
  schedule:
    - cron: "30 */12 * * *"

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        boards: [
                  {boardname: "mochi_uf2/nrf52833", clk: "enabled", type: "tracker", extraaction: "enabled", fileformat: "hex", filename: "SlimeNRF_Tracker_Mochi", mergehex: "https://github.com/Shine-Bright-Meow/Adafruit_nRF52_Bootloader/releases/download/0.9.2-SlimeVR.7/mochaelec_mochi_bootloader-0.9.2-SlimeVR.7_s140_7.3.0.hex", magnetometer: "disabled", sleep: "enabled", sw0: "enabled"}, 
                  {boardname: "mochi_uf2/nrf52833", clk: "enabled", type: "tracker", extraaction: "enabled", fileformat: "hex", filename: "SlimeNRF_Tracker_NoSleep_Mochi", mergehex: "https://github.com/Shine-Bright-Meow/Adafruit_nRF52_Bootloader/releases/download/0.9.2-SlimeVR.7/mochaelec_mochi_bootloader-0.9.2-SlimeVR.7_s140_7.3.0.hex", magnetometer: "disabled", sleep: "disabled", sw0: "enabled"}, 
                ]
    if: always()
    runs-on: ubuntu-latest
    steps:

      - name: üíª Acquire code
        if: always()
        uses: actions/checkout@v5

      - name: üìù Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: üßπ Clean Landing Site
        run: |
          sudo rm -rf zephyr-workspace/SlimeNRF-CI
      - uses: actions/checkout@v5
        with:
          # Clone the repo to a subdirectory, so we can initialize the Zephyr
          # workspace in the parent directory.
          path: zephyr-workspace/SlimeNRF-CI

      - name: üß∞ Install Dependencies + West
        # Install the Zephyr host build dependencies, and the `west` Python tool. This list is from
        # https://docs.zephyrproject.org/3.6.0/develop/getting_started/index.html#install-dependencies
        run: |
          sudo apt-get update && sudo apt install --no-install-recommends \
          git \
          cmake \
          ninja-build \
          gperf \
          ccache \
          dfu-util \
          device-tree-compiler \
          wget \
          python3-dev \
          python3-pip \
          python3-setuptools \
          python3-tk \
          python3-wheel \
          python3-venv \
          xz-utils \
          file \
          make \
          gcc \
          gcc-multilib \
          g++-multilib \
          libsdl2-dev \
          libmagic1 \
          srecord

          python3 -m venv ~/.venv
          source ~/.venv/bin/activate
          # insert the PATH changes the venv activate made to be present for
          # future steps
          echo "PATH=$PATH" >> $GITHUB_ENV
          pip3 install west ninja

      - name: ü™Å Install Zephyr SDK
        # Fetch the Zephyr SDK from the GitHub Release artifact, unpack it and
        # run the setup script, selecting the '-c' option to install cmake
        # packages and the '-t arm-zephyr-eabi' option to install the toolchain
        # only for the arm-zephyr-eabi (Cortex-M) architecture, since we don't
        # need the other toolchains (xtensa, riscv, etc.)
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.17.2/zephyr-sdk-0.17.2_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.17.2_linux-x86_64_minimal.tar.xz -C ~/
          ~/zephyr-sdk-0.17.2/setup.sh -c -t arm-zephyr-eabi
      - name: üß© Install Nordic CLI Tools
        run: |
          wget -qO nrf-command-line-tools.tar.gz https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/desktop-software/nrf-command-line-tools/sw/versions-10-x-x/10-24-2/nrf-command-line-tools-10.24.2_linux-amd64.tar.gz
          tar -xzf nrf-command-line-tools.tar.gz
          sudo cp nrf-command-line-tools/bin/mergehex /usr/local/bin/
          sudo cp nrf-command-line-tools/bin/nrfjprog /usr/local/bin/
          sudo chmod +x /usr/local/bin/mergehex
          sudo chmod +x /usr/local/bin/nrfjprog

      - name: ‚ôªÔ∏è Initialize Zephyr Workspace
        # Set up the Zephyr workspace and install the Python dependencies
        run: |
          cd zephyr-workspace
          sudo rm -rf .west
          west init -l SlimeNRF-CI
          west update --narrow -o=--depth=1
          west zephyr-export

      - name: üêç Install Python Dependencies
        run: |
          cd zephyr-workspace
          pip3 install -r zephyr/scripts/requirements.txt

      - name: üîß Preparing Build Environment
        if: always()
        run: |
          cd zephyr-workspace
          sudo rm -rf Releases
          mkdir Releases

      - name: üî® Build SlimeVR-Tracker-nRF-Receiver - ${{ matrix.boards.boardname }}
      # Receiver Firmware Build 
        if: ${{ matrix.boards.type == 'receiver' }}
        run: |
          cd zephyr-workspace
          sudo rm -rf SlimeVR-Tracker-nRF-Receiver/build
          mkdir SlimeVR-Tracker-nRF-Receiver/build

          west build \
              --board ${{ matrix.boards.boardname }} \
              --pristine=always SlimeVR-Tracker-nRF-Receiver \
              --build-dir SlimeVR-Tracker-nRF-Receiver/build \
              -- \
              -DNCS_TOOLCHAIN_VERSION=NONE \
              -DBOARD_ROOT=../SlimeVR-Tracker-nRF-Receiver

          mv SlimeVR-Tracker-nRF-Receiver/build/SlimeVR-Tracker-nRF-Receiver/zephyr/zephyr.${{ matrix.boards.fileformat }} Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}

      - name: üîß Disabling External Clock
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.clk == 'disabled') }}
        run: |
          cd zephyr-workspace
          find='clk-gpios[ \t]='
          replace='// clk-gpios ='
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble_nrf52840_sense.overlay
          sed -i "s|$find|$replace|g" Stacked-SmolSlime/boards/nordic/promicro_uf2/promicro_uf2.dts
          printf "\n\nCONFIG_USE_SENSOR_CLOCK=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_SENSOR_CLOCK=n" >> Stacked-SmolSlime/prj.conf

      - name: üîß Enabling External Clock
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.clk == 'enabled') }}
        run: |
          cd zephyr-workspace
          find="\/\/\sclk-gpios"
          replace="clk-gpios"
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          sed -i "s/$find/$replace/g" Stacked-SmolSlime/boards/nordic/promicro_uf2/promicro_uf2.dts
          printf "\n\nCONFIG_USE_SENSOR_CLOCK=y" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_SENSOR_CLOCK=y" >> Stacked-SmolSlime/prj.conf

      - name: üîß Disabling Extra Action
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.extraaction == 'disabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USER_EXTRA_ACTIONS=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USER_EXTRA_ACTIONS=n" >> Stacked-SmolSlime/prj.conf

      - name: üîß Enabling Extra Action
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.extraaction == 'enabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USER_EXTRA_ACTIONS=y" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USER_EXTRA_ACTIONS=y" >> Stacked-SmolSlime/prj.conf

      - name: üîß Disabling Magnetometer
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.magnetometer == 'disabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_SENSOR_USE_MAG=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_SENSOR_USE_MAG=n" >> Stacked-SmolSlime/prj.conf

      - name: üîß Enabling Magnetometer
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.magnetometer == 'enabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_SENSOR_USE_MAG=y" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_SENSOR_USE_MAG=y" >> Stacked-SmolSlime/prj.conf

      - name: üîß Disabling Sleep
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sleep == 'disabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USE_IMU_WAKE_UP=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_ACTIVE_TIMEOUT=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_SENSOR_LP_TIMEOUT=300000" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_SENSOR_USE_LOW_POWER_2=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_IMU_WAKE_UP=n" >> Stacked-SmolSlime/prj.conf
          printf "\n\nCONFIG_USE_ACTIVE_TIMEOUT=n" >> Stacked-SmolSlime/prj.conf
          printf "\n\nCONFIG_SENSOR_LP_TIMEOUT=300000" >> Stacked-SmolSlime/prj.conf
          printf "\n\nCONFIG_SENSOR_USE_LOW_POWER_2=n" >> Stacked-SmolSlime/prj.conf

      - name: üîß Enabling Sleep
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sleep == 'enabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USE_IMU_WAKE_UP=y" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_ACTIVE_TIMEOUT=y" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_IMU_WAKE_UP=y" >> Stacked-SmolSlime/prj.conf
          printf "\n\nCONFIG_USE_ACTIVE_TIMEOUT=y" >> Stacked-SmolSlime/prj.conf

      - name: üîß Disabling SW0 Button
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sw0 == 'disabled') }}
        run: |
          cd zephyr-workspace
          find='sw0[ \t]='
          replace='// sw0 ='
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble_nrf52840_sense.overlay
          sed -i "s|$find|$replace|g" Stacked-SmolSlime/boards/nordic/promicro_uf2/promicro_uf2.dts

      - name: üîß Enabling SW0 Button
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sw0 == 'enabled') }}
        run: |
          cd zephyr-workspace
          find='\/\/\ssw0\s='
          replace='sw0 ='
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/xiao_ble_nrf52840_sense.overlay
          sed -i "s/$find/$replace/g" Stacked-SmolSlime/boards/nordic/promicro_uf2/promicro_uf2.dts

      - name: üî® Build SlimeVR-Tracker-nRF - ${{ matrix.boards.boardname }}
      # Tracker Firmware Build 
        if: ${{ (matrix.boards.type == 'tracker') && (!contains(matrix.boards.filename, 'Stacked')) }}
        run: |
          cd zephyr-workspace
          sudo rm -rf SlimeVR-Tracker-nRF/build
          mkdir SlimeVR-Tracker-nRF/build

          west build \
              --board ${{ matrix.boards.boardname }} \
              --pristine=always SlimeVR-Tracker-nRF \
              --build-dir SlimeVR-Tracker-nRF/build \
              -- \
              -DNCS_TOOLCHAIN_VERSION=NONE \
              -DBOARD_ROOT=../SlimeVR-Tracker-nRF

          mv SlimeVR-Tracker-nRF/build/SlimeVR-Tracker-nRF/zephyr/zephyr.${{ matrix.boards.fileformat }} Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}

      - name: üî® Build Stacked-SmolSlime - ${{ matrix.boards.boardname }}
      # Tracker Firmware Build 
        if: ${{ (matrix.boards.type == 'tracker') && (contains(matrix.boards.filename, 'Stacked')) }}
        run: |
          cd zephyr-workspace
          sudo cp -r SlimeVR-Tracker-nRF/vqf-c Stacked-SmolSlime/
          sudo cp -r SlimeVR-Tracker-nRF/Fusion Stacked-SmolSlime/
          sudo cp -r SlimeVR-Tracker-nRF/NXP-ISSDK-SensorFusion Stacked-SmolSlime/
          sudo rm -rf Stacked-SmolSlime/build
          mkdir Stacked-SmolSlime/build

          west build \
              --board ${{ matrix.boards.boardname }} \
              --pristine=always Stacked-SmolSlime \
              --build-dir Stacked-SmolSlime/build \
              -- \
              -DNCS_TOOLCHAIN_VERSION=NONE \
              -DBOARD_ROOT=../Stacked-SmolSlime

          mv Stacked-SmolSlime/build/Stacked-SmolSlime/zephyr/zephyr.${{ matrix.boards.fileformat }} Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}

      - name: üîÄ Merge Hex - ${{ matrix.boards.boardname }}
      # Combining Bootloader and Firmware Build
        if: ${{ (matrix.boards.fileformat == 'hex') && (matrix.boards.mergehex != '') }}
        run: |
          cd zephyr-workspace/Releases
          mv ${{ matrix.boards.filename }}.hex zephyr.hex
          wget -O bootloader.hex ${{ matrix.boards.mergehex }}
          printf ":02000004000FEC\n:04F0000001000000B1\n:00000001FF\n" > skip_crc.hex
          mergehex --ihex zephyr.hex --bin zephyr.bin
          mergehex -m bootloader.hex -b 0x1000 zephyr.bin crc_skip.hex -o ${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
          rm bootloader.hex zephyr.hex skip_crc.hex

      - name: üíæ Upload Artifact - ${{ matrix.boards.boardname }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: ${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
          # A file, directory or wildcard pattern that describes what to upload
          path: zephyr-workspace/Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}

      - name: üìÅ Create/Update Github Release
        if: always()
        uses: mini-bomba/create-github-release@v1.2.0
        with:
          token: ${{ secrets.gh_token }}
          tag: "latest"
          prerelease: false
          name: "Latest Firmware"
          body: |
            Successful build of the latest SlimeNRF Firmware. (Automated)
          files: |
            zephyr-workspace/Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
          clear_attachments: false
